task 1 create entry
chrisahn1/code-journal pull request #5
Opened 2021-12-03 04:29 UTC by chrisahn1

![code journal create entry task 1](https://user-images.githubusercontent.com/22688744/144545394-2e80de44-b6f2-41b5-9805-a3d1fcc7d370.png)

2021-12-07 01:41 UTC, chrisahn1 commented
![code journal local storage](https://user-images.githubusercontent.com/22688744/144950385-f828e7d1-b1b5-4f04-ae8b-fded6908c688.png)
![code journal desktop and phone display](https://user-images.githubusercontent.com/22688744/144950389-6c5208bd-8d54-4cd9-8f1b-35c88924ef84.gif)
![code journal input](https://user-images.githubusercontent.com/22688744/144950393-98fbf791-dbbb-401d-97df-2f578fb77d5f.gif)

2021-12-07 01:47 UTC, chrisahn1 commented
All tasks under task 6 is counted as task 6 so task 7 starts with verifying new entries that are saved in the local storage.

2021-12-08 05:16 UTC, Zhiwutian requested changes
looks good! the only updates are to move the media queries and to change push to unshift for moving the entries into the array

2021-12-08 05:16 UTC, Zhiwutian commented on index.html
> +    @media screen and (min-width: 568px) {
make sure to move the media queries into the styles.css file

2021-12-08 05:35 UTC, Zhiwutian approved these changes
👍🏼

2021-12-09 21:01 UTC, merged